// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyscwsinhvrxwnftvvuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5c2N3c2luaHZyeHduZnR2dnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTQ0NTYsImV4cCI6MjA2OTMzMDQ1Nn0.26_62r5DsXdq9_KGvVpN9TmujLAggpicESTeh8RUYIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});